// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sozmocjngxbhvgxdncqq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNvem1vY2puZ3hiaHZneGRuY3FxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU1NTUyMzUsImV4cCI6MjA1MTEzMTIzNX0.QzcjWbJZI5Q0rAov5Ju3x3T2IC8cFbR5jlNlSMj70sc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);